// lib/main.dart
//
// Entry point for the Firebase-migrated database demo.
//
// Two things are different from the SQLite version:
//
//   1. We must call WidgetsFlutterBinding.ensureInitialized() and
//      Firebase.initializeApp() BEFORE runApp. This is non-negotiable —
//      Firebase needs to set up its native plugins on the platform side
//      before any Firestore call can succeed.
//
//   2. We need a generated firebase_options.dart file (created by running
//      `flutterfire configure` once on your machine). It exports a
//      DefaultFirebaseOptions class with platform-specific config.
//      The README walks through that setup step by step.
//
// If you run this without doing the FlutterFire setup, you'll see the
// error message "[core/no-app] No Firebase App '[DEFAULT]' has been
// created" — that's your signal you missed step 2 of the setup.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`
import 'screens/home_screen.dart';

Future<void> main() async {
  // ensureInitialized lets us use the binding before runApp — required
  // because Firebase.initializeApp itself uses platform channels.
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firebase Database Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.amber),
      ),
      home: const HomeScreen(title: 'Firestore Demo'),
    );
  }
}
